### ISSUE TITLE
[PE-D][Tester E] Order of Prefixes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-3/tp#141]
![Screenshot 2022-10-28 at 4.08.30 PM.png](https://raw.githubusercontent.com/sjoann/ped/main/files/02d587d6-b6ad-425e-9a54-340f86defd94.png)

Some commands require n/ while some require /n which become confusing for the user. It becomes hard to use as the using n/ instead of /n will throw an error. Not sure why there is a need to have 2 different orderings.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: sjoann/ped#2

**Comment by Ryan-Tan00** [comment]
Having a '/' after is meant for parameters that should be filled in (i.e. `name`, `phone`, `emails` etc.) so that the application can store that data.

Having a '/' before is meant for specifying what criterion the `get` command should use to obtain the data stored.

Notably, only `get` commands require the '/' before, making it easier for users to get used to.
